
# ~/.config/starship.toml

# Use custom format
#format = '''
#[┌───────────────────>](fg:snow bg:gray) $git_branch$git_commit$git_status
#[│](snow) 󰘧:$directory$golang$python$java$c$rust$package
#[└─󰤄](snow) '''
#
## Wait 10 milliseconds for starship to check files under the current directory.
#scan_timeout = 10
#
## Disable the blank line at the start of the prompt
#add_newline = false
#
## Set 'foo' as custom color palette
#palette = 'foo'
#
## Define custom colors
#[palettes.foo]
## Overwrite existing color
#blue = '21'
## Define new color
#snow = '#f9cd18'


format = """
[░▒▓](#7a7d7d)\
[ 󰣇 ](bg:#7a7d7d fg:#090c0c)\
[](bg:#d0cfcf fg:#7a7d7d)\
$directory\
[](fg:#d0cfcf bg:#565254)\
$git_branch\
$git_status\
[](fg:#565254 bg:#212121)\
$python\
$java\
$golang\
$c\
[](fg:#212121 bg:#3b3e3d)\
$time\
[ ](fg:#3b3e3d)\
\n$character"""

[directory]
style = "fg:#090c0c bg:#d0cfcf"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = ""

[git_branch]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol $branch ](fg:#090c0c bg:#565254)]($style)'

[git_status]
style = "bg:#212121"
format = '[[($all_status$ahead_behind )](fg:#090c0c bg:#565254)]($style)'

[golang]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#d0cfcf bg:#212121)]($style)'
[c]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#d0cfcf bg:#212121)]($style)'
[java]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#d0cfcf bg:#212121)]($style)'
[python]
symbol = ""
style = "bg:#212121"
format = '[[ $symbol ($version) ](fg:#d0cfcf bg:#212121)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#090c0c bg:#3b3e3d)]($style)'
